Bump compatibility requirements to 2020.2.
We're using API that's only available since that version:

> Method Concepts.Types.lambda$hasMethodAnnotatedWith$9(...) contains an invokeinterface instruction referencing an unresolved method PsiAnnotation.resolveAnnotationType(). This can lead to NoSuchMethodError exception at runtime.